/**
 * ABCProduct
 * ABCProduct 在庫の検索API
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("StockApi", () => {
  let instance: api.StockApi
  beforeEach(function() {
    instance = new api.StockApi(config)
  });

  test("stockGet", () => {
    return expect(instance.stockGet({})).resolves.toBe(null)
  })
  test("stockProductIdGet", () => {
    const productId: number = 789
    return expect(instance.stockProductIdGet(productId, {})).resolves.toBe(null)
  })
})

