/**
 * ABCProduct
 * ABCProduct 在庫の検索API
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("StockApi", () => {
  let instance: api.StockApi
  beforeEach(function() {
    instance = new api.StockApi(config)
  });

  test("stockDeleteIdGet", () => {
    const id: number = 789
    return expect(instance.stockDeleteIdGet(id, {})).resolves.toBe(null)
  })
  test("stockDetailIdGet", () => {
    const id: number = 789
    return expect(instance.stockDetailIdGet(id, {})).resolves.toBe(null)
  })
  test("stockSearchCountsCountsGet", () => {
    const counts: number = 789
    return expect(instance.stockSearchCountsCountsGet(counts, {})).resolves.toBe(null)
  })
  test("stockSearchIdIdGet", () => {
    const id: number = 789
    return expect(instance.stockSearchIdIdGet(id, {})).resolves.toBe(null)
  })
  test("stockSearchItemNameItemNameGet", () => {
    const itemName: string = B
    return expect(instance.stockSearchItemNameItemNameGet(itemName, {})).resolves.toBe(null)
  })
  test("stockSearchPricePriceGet", () => {
    const price: number = 789
    return expect(instance.stockSearchPricePriceGet(price, {})).resolves.toBe(null)
  })
  test("stockSearchWarehouseNameWarehouseNameGet", () => {
    const warehouseName: string = B
    return expect(instance.stockSearchWarehouseNameWarehouseNameGet(warehouseName, {})).resolves.toBe(null)
  })
})

