/**
 * ABCProduct
 * ABCProduct API
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("StockApi", () => {
  let instance: api.StockApi
  beforeEach(function() {
    instance = new api.StockApi(config)
  });

  test("stockAddPost", () => {
    const body: api.Stocks = undefined
    return expect(instance.stockAddPost(body, {})).resolves.toBe(null)
  })
  test("stockDetailProductIdDelete", () => {
    const productId: number = 56
    return expect(instance.stockDetailProductIdDelete(productId, {})).resolves.toBe(null)
  })
  test("stockDetailProductIdGet", () => {
    const productId: number = 56
    return expect(instance.stockDetailProductIdGet(productId, {})).resolves.toBe(null)
  })
  test("stockGet", () => {
    return expect(instance.stockGet({})).resolves.toBe(null)
  })
  test("stockKeywordGet", () => {
    const keyword: string = "keyword_example"
    return expect(instance.stockKeywordGet(keyword, {})).resolves.toBe(null)
  })
})

