openapi: 3.0.0
info:
  title: ABCProduct
  description: ABCProduct 在庫の検索API
  version: 0.1.9
servers:
- url: /
tags:
- name: stock
  description: 在庫の検索
paths:
  /stock/search/id/{id}:
    get:
      tags:
      - stock
      summary: 在庫ID検索
      description: 在庫IDの検索結果
      operationId: stockSearchIdIdGET
      parameters:
      - name: id
        in: path
        description: 在庫ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: 在庫IDは無効です
        "404":
          description: 在庫IDが見つかりませんでした
        default:
          description: 予期しないエラー
      x-swagger-router-controller: Stock
  /stock/search/itemName/{itemName}:
    get:
      tags:
      - stock
      summary: 商品名の検索
      description: 商品名の検索結果
      operationId: stockSearchItemNameItemNameGET
      parameters:
      - name: itemName
        in: path
        description: 商品名
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: byte
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: 商品名は無効です
        "404":
          description: 商品名が見つかりませんでした
        default:
          description: 予期しないエラー
      x-swagger-router-controller: Stock
  /stock/search/counts/{counts}:
    get:
      tags:
      - stock
      summary: 商品数の検索
      description: 商品数の検索結果
      operationId: stockSearchCountsCountsGET
      parameters:
      - name: counts
        in: path
        description: 商品数
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: 商品数は無効です
        "404":
          description: 商品数が見つかりませんでした
        default:
          description: 予期しないエラー
      x-swagger-router-controller: Stock
  /stock/search/warehouseName/{warehouseName}:
    get:
      tags:
      - stock
      summary: 倉庫名の検索
      description: 倉庫名の検索結果
      operationId: stockSearchWarehouseNameWarehouseNameGET
      parameters:
      - name: warehouseName
        in: path
        description: 倉庫名
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: byte
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: 倉庫名は無効です
        "404":
          description: 倉庫名が見つかりませんでした
        default:
          description: 予期しないエラー
      x-swagger-router-controller: Stock
  /stock/search/price/{price}:
    get:
      tags:
      - stock
      summary: 単価の検索
      description: 単価の検索結果
      operationId: stockSearchPricePriceGET
      parameters:
      - name: price
        in: path
        description: 単価
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: 単価は無効です
        "404":
          description: 単価が見つかりませんでした
        default:
          description: 予期しないエラー
      x-swagger-router-controller: Stock
  /stock/detail/{id}:
    get:
      tags:
      - stock
      summary: 在庫詳細
      description: 在庫詳細の取得
      operationId: stockDetailIdGET
      parameters:
      - name: id
        in: path
        description: 在庫ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: 在庫IDは無効です
        "404":
          description: 在庫IDが見つかりませんでした
        default:
          description: 予期しないエラー
      x-swagger-router-controller: Stock
  /stock/delete/{id}:
    get:
      tags:
      - stock
      summary: 在庫詳細
      description: 在庫詳細の取得
      operationId: stockDeleteIdGET
      parameters:
      - name: id
        in: path
        description: 在庫ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: 在庫IDは無効です
        "404":
          description: 在庫IDが見つかりませんでした
        default:
          description: 予期しないエラー
      x-swagger-router-controller: Stock
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        id:
          type: integer
          format: int64
        itemId:
          type: integer
          format: int64
        itemName:
          type: string
          format: byte
        warehouseId:
          type: integer
          format: int64
        warehouseName:
          type: string
          format: byte
        counts:
          type: integer
          format: int64
        price:
          type: integer
          format: int64
      example:
        itemId: 6
        itemName: ""
        warehouseId: 1
        counts: 5
        price: 5
        id: 0
        warehouseName: ""
    inline_response_200_1:
      type: object
      properties:
        deleteCount:
          type: integer
          format: int64
      example:
        deleteCount: 0
